/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class Menu_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Administrador
     */
    //variable global
    Usuario user;
    //constructor con parametros
    public Menu_Administrador(Usuario usuario) {
        initComponents();
        this.user=usuario;
    }
    //contructor 
     public Menu_Administrador() {
        initComponents();
        Color miColorPersonalizado = new Color(40, 40, 40);
        jPanel1.setBackground(miColorPersonalizado);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JPanelAcceso = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdministarDoc = new javax.swing.JButton();
        btnAdminEstudiantes = new javax.swing.JToggleButton();
        adminMatricula = new javax.swing.JButton();
        AdminPeriodo = new javax.swing.JButton();
        AdminAsignatura = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Exit");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, 0, 0));
        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        JPanelAcceso.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPanelAccesoLayout = new javax.swing.GroupLayout(JPanelAcceso);
        JPanelAcceso.setLayout(JPanelAccesoLayout);
        JPanelAccesoLayout.setHorizontalGroup(
            JPanelAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        JPanelAccesoLayout.setVerticalGroup(
            JPanelAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        getContentPane().add(JPanelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 810, 740));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENU.png"))); // NOI18N
        jLabel1.setToolTipText("");

        btnAdministarDoc.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnAdministarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/45109776-suscriptores-seguidores-usuarios-icono-vector-también-image-can-utilizarse-para-admin-salpicadero(3).jpg"))); // NOI18N
        btnAdministarDoc.setText("Administrar Docentes");
        btnAdministarDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministarDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministarDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdministarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministarDocActionPerformed(evt);
            }
        });

        btnAdminEstudiantes.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnAdminEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/communities-line-green-and-black-icon-vector.jpg"))); // NOI18N
        btnAdminEstudiantes.setText("Administar Estudiantes");
        btnAdminEstudiantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminEstudiantes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdminEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminEstudiantesActionPerformed(evt);
            }
        });

        adminMatricula.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        adminMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo-con-una-persona-y-una-marca-de-verificacion-verde-2k2fm87.jpg"))); // NOI18N
        adminMatricula.setText("Administrar Matriculas");
        adminMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminMatricula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        adminMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMatriculaActionPerformed(evt);
            }
        });

        AdminPeriodo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        AdminPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images(1).jpeg"))); // NOI18N
        AdminPeriodo.setText("Administrar Periodos Academicos");
        AdminPeriodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminPeriodo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AdminPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPeriodoActionPerformed(evt);
            }
        });

        AdminAsignatura.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        AdminAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-flat-green-laptop-icon-with-computer-screen-answer-fill-form-vector-png-image_12719274.png"))); // NOI18N
        AdminAsignatura.setText("Administrar Asignaturas");
        AdminAsignatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminAsignatura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AdminAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAsignaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AdminPeriodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(adminMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdminEstudiantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnAdministarDoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminAsignatura))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdministarDoc)
                .addGap(18, 18, 18)
                .addComponent(btnAdminEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AdminPeriodo)
                .addGap(24, 24, 24)
                .addComponent(AdminAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPeriodoActionPerformed

    private void AdminAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminAsignaturaActionPerformed

    private void adminMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMatriculaActionPerformed

    private void btnAdminEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminEstudiantesActionPerformed

    private void btnAdministarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministarDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AdminAsignatura;
    private javax.swing.JButton AdminPeriodo;
    private javax.swing.JPanel JPanelAcceso;
    private javax.swing.JButton adminMatricula;
    private javax.swing.JToggleButton btnAdminEstudiantes;
    private javax.swing.JButton btnAdministarDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
